title: Madhura Gurav
logo: "github_logo1.PNG" 

description: > # your text below (remove <br> elements if you don't need line breaks)
  Spatial Data Scientist 
  <br><br>
  Geoscientist
  <br><br>
  I like data and I'm interested in how data can be used to shape decisions and improve communities!
  <br><br>
  Master of Urban Spatial Analytics - University of Pennsylvania
  <br><br>
  Master of Science in Applied Geosciences - University of Pennsylvania
  <br><br>
  <a href="https://www.linkedin.com/in/madhura-gurav-ab1084136/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 
