title: Madhura Gurav
logo: "github_logo.PNG" 

description: > # your text below (remove <br> elements if you don't need line breaks)
  Spatial Data Scientist (Python / R / SQL / ArcGIS)
  <br>
  Hydrogeologist
  <br><br>
  Master of Urban Spatial Analytics
  <br>
  -University of Pennsylvania
  <br>
  Master of Science in Applied Geosciences
  <br>
  -University of Pennsylvania
  <br><br>
  <a href="https://www.linkedin.com/in/madhura-gurav-ab1084136/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 
